<div class="main">
		<div class="header">
            <div id="topMenu">
                     <ul>
                    	$user$
                    	$setting$
                    	$userhistory$                        
                        $logout$
                    </ul>
        	 </div>
        	 <div class="clear"></div>
        </div>
        <div class="body_small">
        	<table class="body_bar">
            	<tbody>
            	<tr>
                    <td align="center"><h2>Personal Account Setting</h2></td>
                </tr>
                <tr>
                    <td><div class="title_small"><a href="/index"><img src="logo_small.jpg" /></a></div></td>
                </tr>
                <tr>
                	<td>
        				<ul style="margin-left:30; margin-top:30">
        					<li>
        						<a href="/account/changepw">change password</a>
        					</li>
        					<li>
        						<a href="/account/cleanhistory">clear history</a>
        					</li>
							<li>
        						<a href="/account/changenumpage">change number of links in a page</a>
        					</li>
        					$admin$
        				</ul>
        			</td>
        		</tr>
        	</table>
        </div>
        <div class="footer">
            <div>
                <ul>
                    <li>Zapper 2010 - Copy Right by Leo</li>                    
                </ul>
             </div>
        </div>
    </div> 
