<div class="main">
        <div class="header">
            <div id="topMenu">
                    <ul>
                    	$user$
                    	$setting$
                    	$userhistory$                        
                        $logout$
                    </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div class="body">
            <div class="title_small"><a href="/index"><img src="$zapperlogo$" /></a></div>
            <div class="searchBox">
            	<form id="f" action="/account/changenumpage" method="post">
                    <b>How many links in a page :</b> <input type="text" title="number" name="num" id="num" maxlength="2048" size="20" />
                    <input type="button" name="c" id="c" value="Submit" onClick="javascript:changeNum();"/>                
            	</form>
            </div>
        </div>
        <div class="footer">
            <div>
                <ul>
                    <li>Zapper 2010 - Copy Right by Leo</li>                    
                </ul>
             </div>
        </div>
</div> 