<div class="main">
        <div class="header">
            <div id="topMenu">
                    <ul>
                    	$user$
                    	$setting$
                    	$userhistory$                        
                        $logout$
                    </ul>
            </div>
            <div class="clear"></div>
        </div>
        <div class="body">
            <div class="title"><img src="login.jpg" /></div>
            <div class="searchBox">
               <form id="f" action="/search">
                    <input type="text" title="zoomer search" name="q" id="q" maxlength="2048" size="80" />
                    <input type="submit" name="s" id="s" value="Search"/>                
                </form>
            </div>
        </div>
        <div class="footer">
            <div>
                <ul>
                    <li>Zapper 2010 - Copy Right by Leo</li>                    
                </ul>
             </div>
        </div>
</div> 